import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import { cn } from "@/lib/utils";
import LayoutProvider from "@/components/LayoutProvider";
import { fetchData } from "@/lib/FetchData";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const data = await fetchData("https://6zmy2apr.api.sanity.io/v2022-03-07/data/query/production?query=*%5B_type+%3D%3D+%22footer%22%5D%5B0%5D")

  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-secondary !tracking-tighter")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          <LayoutProvider data={data}>{children}</LayoutProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
